name: portfolio_phase2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gal: ^2.3.3
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  # Portfolio background image
  assets:
    - assets/portfolio_bg.jfif

# App icon settings
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
